production:
  solr:
    hostname: us-west-2.websolr.com
    port: 80
    log_level: WARNING
    path: /solr/9b9106cd2da
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    